services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "admin12345*"
      ACCEPT_EULA: "Y"

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=StoreSample;User Id=sa;Password=admin12345*;TrustServerCertificate=True;

networks:
  shared_network:
    name: mynetwork
    external: true

